package com.owusu.cryptosignalalert.workmanager

object Constants {

    val SYNC_PRICES_WORKER_TAG = "SyncPriceTargetsWorker"
    val KEY_PRICE_TARGET_UPDATED_STATUS = "KEY_PRICE_TARGET_UPDATED"
    val PRICE_TARGET_UPDATED = "PRICE_TARGET_UPDATED"
    val PRICE_TARGET_NOT_UPDATED = "PRICE_TARGET_NOT_UPDATED"
    val DISPLAY_LATEST_DATA = "DISPLAY_LATEST_DATA"
}